// duolingoWords.ts

// duolingoWords.ts

export const duolingoWords = [
    { english: 'green tea', romanji: 'ocha', hiragana: 'おちゃ', kanji: 'お茶' },
    { english: 'please', romanji: 'kudasai', hiragana: 'ください', kanji: 'N/A' },
    { english: 'sushi', romanji: 'sushi', hiragana: 'すし', kanji: '寿司' },
    { english: 'rice', romanji: 'gohan', hiragana: 'ごはん', kanji: 'ご飯' },
    { english: 'water', romanji: 'mizu', hiragana: 'みず', kanji: '水' },
    { english: 'and', romanji: 'to', hiragana: 'と', kanji: 'N/A' },
    { english: 'doctor', romanji: 'isha', hiragana: 'いしゃ', kanji: '医者' },
    { english: 'teacher', romanji: 'sensei', hiragana: 'せんせい', kanji: '先生' },
    { english: 'lawyer', romanji: 'bengoshi', hiragana: 'べんごし', kanji: '弁護士' },
    { english: 'cool', romanji: 'kakkoii', hiragana: 'かっこいい', kanji: 'N/A' },
    { english: 'person', romanji: 'hito', hiragana: 'ひと', kanji: '人' },
    { english: 'student', romanji: 'gakusei', hiragana: 'がくせい', kanji: '学生' },
    { english: 'hello', romanji: 'konnichiwa', hiragana: 'こんにちは', kanji: 'N/A' },
    { english: 'bye', romanji: 'jaane', hiragana: 'じゃあね', kanji: 'N/A' },
    { english: 'curry', romanji: 'karee', hiragana: 'カレー', kanji: 'N/A' },
    { english: 'delicious', romanji: 'oishii', hiragana: 'おいしい', kanji: '美味しい' },
    { english: 'ramen', romanji: 'raamen', hiragana: 'ラーメン', kanji: 'N/A' },
    { english: 'this (as subject)', romanji: 'kore', hiragana: 'これ', kanji: 'N/A' },
    { english: 'these (as subject)', romanji: 'korera', hiragana: 'これら', kanji: 'N/A' },
    { english: 'that (as subject)', romanji: 'sore', hiragana: 'それ', kanji: 'N/A' },
    { english: 'those (as subject)', romanji: 'sorera', hiragana: 'それら', kanji: 'N/A' },
    { english: 'pizza', romanji: 'piza', hiragana: 'ピザ', kanji: 'N/A' },
    { english: 'cake', romanji: 'keeki', hiragana: 'ケーキ', kanji: 'N/A' },
    { english: 'yes', romanji: 'hai', hiragana: 'はい', kanji: 'N/A' },
    { english: 'no', romanji: 'iie', hiragana: 'いいえ', kanji: 'N/A' },
    { english: 'big', romanji: 'ookii', hiragana: 'おおきい', kanji: '大きい' },
    { english: 'japan', romanji: 'nihon', hiragana: 'にほん', kanji: '日本' },
    { english: 'small', romanji: 'chiisai', hiragana: 'ちいさい', kanji: '小さい' },
    { english: 'america', romanji: 'amerika', hiragana: 'アメリカ', kanji: 'N/A' },
    { english: 'canada', romanji: 'kanada', hiragana: 'カナダ', kanji: 'N/A' },
    { english: 'american', romanji: 'amerikajin', hiragana: 'アメリカじん', kanji: 'アメリカ人' },
    { english: 'canadian', romanji: 'kanadajin', hiragana: 'カナダじん', kanji: 'カナダ人' },
    { english: 'japanese', romanji: 'nihonjin', hiragana: 'にほんじん', kanji: '日本人' },
    { english: 'britain', romanji: 'igirisu', hiragana: 'イギリス', kanji: 'N/A' },
    { english: 'brazil', romanji: 'burajiru', hiragana: 'ブラジル', kanji: 'N/A' },
    { english: 'british', romanji: 'igirisu-jin', hiragana: 'イギリスじん', kanji: 'イギリス人' },
    { english: 'brazilian', romanji: 'burajiru-jin', hiragana: 'ブラジルじん', kanji: 'ブラジル人' },
    { english: 'where', romanji: 'doko', hiragana: 'どこ', kanji: 'N/A' },
    { english: 'convenience store', romanji: 'konbini', hiragana: 'コンビニ', kanji: 'N/A' },
    { english: 'hotel', romanji: 'hoteru', hiragana: 'ホテル', kanji: 'N/A' },
    { english: 'bus stop', romanji: 'basu-tei', hiragana: 'バスてい', kanji: 'バス停' },
    { english: 'here', romanji: 'koko', hiragana: 'ここ', kanji: 'N/A' },
    { english: 'department store', romanji: 'depāto', hiragana: 'デパート', kanji: 'N/A' },
    { english: 'train station', romanji: 'eki', hiragana: 'えき', kanji: '駅' },
    { english: 'university', romanji: 'daigaku', hiragana: 'だいがく', kanji: '大学' },
    { english: 'there', romanji: 'soko', hiragana: 'そこ', kanji: 'N/A' },
    { english: 'hat', romanji: 'boushi', hiragana: 'ぼうし', kanji: '帽子' },
    { english: 'red', romanji: 'akai', hiragana: 'あかい', kanji: '赤い' },
    { english: 'coat', romanji: 'kooto', hiragana: 'コート', kanji: 'N/A' },
    { english: 'white', romanji: 'shiroi', hiragana: 'しろい', kanji: '白い' },
    { english: 'shoes', romanji: 'kutsu', hiragana: 'くつ', kanji: '靴' },
    { english: 'this (preposition)', romanji: 'kono', hiragana: 'この', kanji: 'N/A' },
    { english: 'cute', romanji: 'kawaii', hiragana: 'かわいい', kanji: 'N/A' },
    { english: 'that (preposition)', romanji: 'sono', hiragana: 'その', kanji: 'N/A' },
    { english: 'interesting/funny', romanji: 'omoshiroi', hiragana: 'おもしろい', kanji: '面白い' },
    { english: 'one', romanji: 'ichi', hiragana: 'いち', kanji: '一' },
    { english: 'two', romanji: 'ni', hiragana: 'に', kanji: '二' },
    { english: 'three', romanji: 'san', hiragana: 'さん', kanji: '三' },
    { english: 'four', romanji: 'yon', hiragana: 'よん', kanji: '四' },
    { english: 'five', romanji: 'go', hiragana: 'ご', kanji: '五' },
    { english: 'six', romanji: 'roku', hiragana: 'ろく', kanji: '六' },
    { english: 'seven', romanji: 'nana', hiragana: 'なな', kanji: '七' },
    { english: "o'clock", romanji: 'ji', hiragana: 'じ', kanji: '時' },
    { english: 'now', romanji: 'ima', hiragana: 'いま', kanji: '今' },
    { english: 'excuse me', romanji: 'sumimasen', hiragana: 'すみません', kanji: 'N/A' },
    { english: 'airport', romanji: 'kuukou', hiragana: 'くうこう', kanji: '空港' },
    { english: 'subway', romanji: 'chikatetsu', hiragana: 'ちかてつ', kanji: '地下鉄' },
    { english: 'ticket', romanji: 'kippu', hiragana: 'きっぷ', kanji: '切符' },
    { english: 'map', romanji: 'chizu', hiragana: 'ちず', kanji: '地図' },
    { english: 'smartphone', romanji: 'sumaho', hiragana: 'スマホ', kanji: 'N/A' },
    { english: 'of (no)', romanji: 'no', hiragana: 'の', kanji: 'N/A' },
    { english: 'passport', romanji: 'passupooto', hiragana: 'パスポート', kanji: 'N/A' },
    { english: 'tanaka', romanji: 'Tanaka', hiragana: 'たなか', kanji: '田中' },
    { english: 'bag', romanji: 'kaban', hiragana: 'かばん', kanji: '鞄' },
    { english: 'good morning', romanji: 'ohayou gozaimasu', hiragana: 'おはようございます', kanji: 'お早うございます' },
    { english: 'welcome', romanji: 'yookoso', hiragana: 'ようこそ', kanji: 'N/A' },
    { english: 'i', romanji: 'watashi', hiragana: 'わたし', kanji: '私' },
    { english: 'also (instead of wa)', romanji: 'mo', hiragana: 'も', kanji: 'N/A' },
    { english: 'new york', romanji: 'Nyū Yōku', hiragana: 'ニューヨーク', kanji: 'N/A' },
    { english: 'kyoto', romanji: 'Kyōto', hiragana: 'きょうと', kanji: '京都' },
    { english: 'osaka', romanji: 'Ōsaka', hiragana: 'おおさか', kanji: '大阪' },
    { english: 'city (toshi)', romanji: 'toshi', hiragana: 'とし', kanji: '都市' },
    { english: 'lively', romanji: 'nigiyaka', hiragana: 'にぎやか', kanji: '賑やか' },
    { english: 'quiet', romanji: 'shizuka', hiragana: 'しずか', kanji: '静か' },
    { english: 'clean', romanji: 'kirei', hiragana: 'きれい', kanji: '綺麗' },
    { english: 'very', romanji: 'totemo', hiragana: 'とても', kanji: 'N/A' },
    { english: 'town (machi)', romanji: 'machi', hiragana: 'まち', kanji: '町' },
    { english: 'mom', romanji: 'haha', hiragana: 'はは', kanji: '母' },
    { english: 'family', romanji: 'kazoku', hiragana: 'かぞく', kanji: '家族' },
    { english: 'dad', romanji: 'chichi', hiragana: 'ちち', kanji: '父' },
    { english: 'engineer', romanji: 'enginea', hiragana: 'エンジニア', kanji: 'N/A' },
    { english: 'busy', romanji: 'isogashii', hiragana: 'いそがしい', kanji: '忙しい' },
    { english: 'years old (sai)', romanji: 'sai', hiragana: 'さい', kanji: '歳' },
    { english: 'my younger sister', romanji: 'imouto', hiragana: 'いもうと', kanji: '妹' },
    { english: 'my older sister', romanji: 'ane', hiragana: 'あね', kanji: '姉' },
    { english: 'office worker', romanji: 'kaishain', hiragana: 'かいしゃいん', kanji: '会社員' },
    { english: 'my older brother', romanji: 'ani', hiragana: 'あに', kanji: '兄' },
    { english: 'noisy', romanji: 'urusai', hiragana: 'うるさい', kanji: '煩い' },
    { english: 'my younger brother', romanji: 'otouto', hiragana: 'おとうと', kanji: '弟' },
    { english: 'nurse', romanji: 'kangoshi', hiragana: 'かんごし', kanji: '看護師' },
    { english: 'famous', romanji: 'yūmei', hiragana: 'ゆうめい', kanji: '有名' },
    { english: 'college student', romanji: 'daigakusei', hiragana: 'だいがくせい', kanji: '大学生' },
    { english: 'my wife', romanji: 'tsuma', hiragana: 'つま', kanji: '妻' },
    { english: 'my daughter', romanji: 'musume', hiragana: 'むすめ', kanji: '娘' }
]